FROM node:18.20.4-alpine
RUN mkdir /app
WORKDIR /app
RUN npm install -g @angular/cli@18.2.1

COPY ./docker/entrypoint-dev.sh /usr/bin/docker-entrypoint.sh

RUN ["chmod", "+x", "/usr/bin/docker-entrypoint.sh"]

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]