version: '2'
services:
  proyecto-prime:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    working_dir: /app
    ports:
      - 4205:4200
    volumes:
      - ./:/app
    command: ["ng","serve", "--host", "0.0.0.0"]
